-- Capacidad: orthodontic-records — datos del paciente fijos tras imprimir (add-patient-identity-lock).
-- patient_locked_at: primera impresión registrada (nulo = desbloqueada; también las impresas antes).
-- unlock_requested_at / unlock_request_reason: solicitud de desbloqueo pendiente del tratante.
-- record_unlock_events: desbloqueos y descartes del ADMIN, solo inserción (rastro).

ALTER TABLE orthodontic_records ADD COLUMN patient_locked_at TIMESTAMPTZ NULL;
ALTER TABLE orthodontic_records ADD COLUMN unlock_requested_at TIMESTAMPTZ NULL;
ALTER TABLE orthodontic_records ADD COLUMN unlock_request_reason VARCHAR(200) NULL;
ALTER TABLE orthodontic_records ADD CONSTRAINT ck_orthodontic_records_unlock_request
    CHECK ((unlock_requested_at IS NULL) = (unlock_request_reason IS NULL));

-- Solicitudes pendientes (Inicio del ADMIN, más antiguas primero).
CREATE INDEX ix_orthodontic_records_unlock_pending ON orthodontic_records (unlock_requested_at)
    WHERE unlock_requested_at IS NOT NULL;

CREATE TABLE record_unlock_events (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    record_id  BIGINT       NOT NULL REFERENCES orthodontic_records (id),
    admin_id   BIGINT       NOT NULL REFERENCES users (id),
    action     VARCHAR(20)  NOT NULL,
    reason     VARCHAR(200),
    created_at TIMESTAMPTZ  NOT NULL,
    CONSTRAINT ck_record_unlock_events_action CHECK (action IN ('UNLOCKED', 'DISCARDED'))
);

CREATE INDEX ix_record_unlock_events_record ON record_unlock_events (record_id, created_at DESC);
