-- Capacidad: orthodontic-records — historia clínica de ortodoncia (fase 1).
-- Columnas para lo que se lista o busca; el contenido clínico va en JSONB (design D1/D2).

CREATE TABLE orthodontic_records (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author_id            BIGINT       NOT NULL REFERENCES users (id),
    record_seq           INT          NOT NULL,
    record_number        VARCHAR(20)  NOT NULL,
    treating_dentist     VARCHAR(120),
    patient_name         VARCHAR(120) NOT NULL,
    document_type        VARCHAR(20),
    document_number      VARCHAR(12),
    patient_sex          VARCHAR(10),
    birth_date           DATE,
    birth_place          VARCHAR(120),
    address              VARCHAR(200),
    phone                VARCHAR(20),
    treatment_start_date DATE,
    search_text          VARCHAR(400) NOT NULL,
    content              JSONB        NOT NULL DEFAULT '{}',
    version              BIGINT       NOT NULL DEFAULT 0,
    created_at           TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at           TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT ux_orthodontic_records_author_seq UNIQUE (author_id, record_seq),
    CONSTRAINT ck_orthodontic_records_document_type
        CHECK (document_type IS NULL OR document_type IN ('DNI', 'FOREIGNER_CARD', 'PASSPORT')),
    CONSTRAINT ck_orthodontic_records_document_pair
        CHECK ((document_type IS NULL) = (document_number IS NULL)),
    CONSTRAINT ck_orthodontic_records_patient_sex
        CHECK (patient_sex IS NULL OR patient_sex IN ('FEMALE', 'MALE'))
);

-- Listado del USER (sus historias) y del ADMIN (todas), por última modificación.
CREATE INDEX ix_orthodontic_records_author_updated ON orthodontic_records (author_id, updated_at DESC);
CREATE INDEX ix_orthodontic_records_updated ON orthodontic_records (updated_at DESC);
